image: coderbase/angular:8

stages:
  - build
  - doc
  - test
  - deploy-doc

build:
    stage: build
    cache:
      paths:
        - node_modules/
    script:
      - npm install --quiet
      - npm run build-prod
    artifacts:
      paths:
        - dist/
doc:
  stage: doc
  script:
    - npm run compodoc-ci
  artifacts:
    paths:
      - documentation/

pages:
  stage: deploy-doc
  script:
  - mkdir .public
  - cp -r documentation/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
  - ng lint
  - ng build --prod && npm run generate
  - npm run cy:verify
  - npm run ci:cy-run

