image: registry.gitlab.com/coderbaseit/crm-grenoble-mai
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - doc
  - test
  - deploy


build:
    stage: build
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules/
        - /root/.cache/Cypress
    script:
      - npm install --quiet --save-dev
      - npm run build-prod
    artifacts:
      paths:
        - dist/

doc:
  stage: build
  script:
    - npm run ci:compodoc
  artifacts:
    paths:
      - documentation/

pages:
  stage: doc
  script:
  - mkdir .public
  - cp -r documentation/* .public
  - mkdir public
  - mv .public public/documentation
  artifacts:
    paths:
    - public
  only:
  - master


test:
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-test:12.1.0
  stage: test
  dependencies:
    - build
  script:
  - npm install
  - ng lint
  - npm run ci:json-server
  - npm run cy:verify
  - npm run ci:cy-run
  artifacts:
    when: on_failure
    expire_in: '1 week'
    paths:
      - cypress/videos
      - cypress/screenshots
  artifacts:
    when: on_success
    expire_in: '3 days'
    paths:
      - cypress/screenshots

deploy-prod:
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-firebase:12.1.0
  stage: deploy
  environment:
    name: prod
    url: https://coderbase-starter.firebaseapp.com
  only:
    - master
  script:
    - firebase use coderbase-starter --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN


# Common build job definition using GitLab YAML features
# http://docs.gitlab.com/ce/ci/yaml/README.html#special-yaml-features

# we will generate the test definitions per spec bundle
# using the common definition

# Hidden job that defines an anchor named 'e2e_test_definition'
# This job will be automatically assigned "test" phase
.job_template: &e2e_test_definition
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-test:12.1.0
  script:
    - npm install -g cypress
    - cypress run --spec cypress/integration/tests/$CI_BUILD_NAME.js

actions_spec:
  <<: *e2e_test_definition

aliasing_spec:
  <<: *e2e_test_definition

assertions_spec:
  <<: *e2e_test_definition

basic_spec:
  <<: *e2e_test_definition

config_spec:
  <<: *e2e_test_definition

connectors_spec:
  <<: *e2e_test_definition

cookies_spec:
  <<: *e2e_test_definition

cookies2_spec:
  <<: *e2e_test_definition

dom_spec:
  <<: *e2e_test_definition

env_spec:
  <<: *e2e_test_definition

fixtures_spec:
  <<: *e2e_test_definition

local-storage_spec:
  <<: *e2e_test_definition

location_spec:
  <<: *e2e_test_definition

misc_spec:
  <<: *e2e_test_definition

navigation_spec:
  <<: *e2e_test_definition

network_spec:
  <<: *e2e_test_definition

querying_spec:
  <<: *e2e_test_definition

server_spec:
  <<: *e2e_test_definition

traversal_spec:
  <<: *e2e_test_definition

utilities_spec:
  <<: *e2e_test_definition

viewport_spec:
  <<: *e2e_test_definition

waiting_spec:
  <<: *e2e_test_definition

window_spec:
  <<: *e2e_test_definition

orders_spec:
  <<: *e2e_test_definition

