image: registry.gitlab.com/coderbaseit/crm-grenoble-mai
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - doc
  - test
  - deploy


build:
    stage: build
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules/
        - /root/.cache/Cypress
    script:
      - npm install --quiet --save-dev
      - npm run build-prod
    artifacts:
      paths:
        - dist/

doc:
  stage: build
  script:
    - npm run compodoc-ci
  artifacts:
    paths:
      - documentation/

pages:
  stage: doc
  script:
  - mkdir .public
  - cp -r documentation/* .public
  - mkdir public
  - mv .public public/documentation
  artifacts:
    paths:
    - public
  only:
  - master


test:
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-test:12.1.0
  stage: test
  dependencies:
    - build
  script:
  - npm install
  - ng lint
  - npm run ci:json-server
  - npm run cy:verify
  - npm run ci:cy-run
  artifacts:
    when: on_failure
    expire_in: '1 week'
    paths:
      - cypress/videos
      - cypress/screenshots
  artifacts:
    when: on_success
    expire_in: '3 days'
    paths:
      - cypress/screenshots

deploy-prod:
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-firebase:12.1.0
  stage: deploy
  environment:
    name: prod
    url: https://coderbase-starter.firebaseapp.com
  only:
    - master
  script:
    - firebase use coderbase-starter --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
