image: registry.gitlab.com/coderbaseit/crm-grenoble-mai
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - doc
  - deploy-doc
  - test


build:
    stage: build
    cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules/
    script:
      - npm ci --quiet --save-dev
      - npm run build-prod
    artifacts:
      paths:
        - dist/
        
doc:
  stage: build
  script:
    - npm run compodoc-ci
  artifacts:
    paths:
      - documentation/

pages:
  stage: deploy-doc
  script:
  - mkdir .public
  - cp -r documentation/* .public
  - mkdir public
  - mv .public public/documentation
  artifacts:
    paths:
    - public
  only:
  - master


test:
  image: registry.gitlab.com/coderbaseit/crm-grenoble-mai/coderbase-test:12.1.0
  stage: test
  dependencies:
    - build
  cache:
      key: ${CI_COMMIT_REF_SLUG}
      paths:
        - node_modules/
  script:
  - npm install
  - ng lint
  - npm run ci:json-server
  - npm run cy:verify
  - npm run ci:cy-run
  artifacts:
    when: on_failure
    expire_in: '1 week'
    untracked: true
    paths:
      - cypress/videos
      - cypress/screenshots
  artifacts:
    when: on_success
    expire_in: '3 days'
    untracked: true
    paths:
      - cypress/screenshots
