image: coderbase/angular:8

stages:
  - build
  - doc

build:
    stage: build
    cache:
      paths:
        - node_modules/
    script:
      - npm install --quiet
      - npm run build-prod
    artifacts:
      paths:
        - dist/
doc:
  stage: doc
  script:
    - npm run compodoc-ci
  artifacts:
    paths:
      - documentation/
