image: coderbase/angular:8

build:
    stage: build
cache:
    paths:
    - node_modules/
    script:
    - npm install --quiet
    - npm run build-prod
artifacts:
    paths:
        - dist/
stage: doc
        script:
- npm run compodoc-ci
artifacts:
    paths:
        - documentation/
